### ISSUE TITLE
How to kill videos when switch new video

### ISSUE THREAD

**Issue by rongconzx** [RReverser/mpegts#10]
Hi guys, 
I have 2 video and every 5 min i switch one video and play it. But i can stop request or kill old video to show new video. It made my web crash when i play over 30 min.
Please have me thank guys !

**Comment by RReverser** [comment]
Sorry, I don't really understand your question nor what you're trying to do. Can you please show code example?

**Comment by rongconzx** [comment]
I have 4 videos play on one page. At the time, i only show 1 video so every 5 min i need to change  next video by call new trigger . So thread worker.js is created consecutive. This is root cause made my web crash. How to can i kill this thead when i change to next video ?

**Comment by RReverser** [comment]
As I asked - can you please show code example? I don't understand why would it crash because of creating separate worker (it shouldn't) nor why you're switching HLS streams at all.

**Comment by rongconzx** [comment]
I found the cause of crashing, it is because virtual memory of browser become 2GB! Now I want to find a way to prevent memory to increase too much.

In my web app, there are SEVERAL videos to be play and each time the web app switch to play a new video, I trigger a 'playVideo' event so that your browser.js code is executed in the corresponding event handler of 'playVideo' event:

```
$(document).on('playVideo' ,function (event, id, canvasID, link) {
            // preconfiguration using <script>'s data-attributes values
    var scripts = document.getElementsByTagName('script'),
    ....
    //Your browser.js code here
    ...
});
```

After triggering playVideo' event several times, memory become huge and browser crash!
I guess that there is other way to play several videos without memory issue?

**Comment by RReverser** [comment]
This lib is not for multiple videos but for HLS video stream.

**Comment by rongconzx** [comment]
Thank for your information. But find new issue for your library. Videos aren't smoothly on chorme new version(version 39) and IE 11 on  window 8. please check it !

**Comment by RReverser** [comment]
Smooth playing of video chunks theirselves has nothing to do with library - it's rather problem with your codecs and/or machine. If you mean not smooth switching - unfortunately, it's not possible to overcome until browsers support Media Streaming Extension with H.264.
