### ISSUE TITLE
Opposite conversion

### ISSUE THREAD

**Issue by guypaskar** [RReverser/mpegts#13]
I was wondering if the opposite conversion is also available.

That is, playing an mpeg4 file in an hls player.

**Comment by RReverser** [comment]
I don't see where it would make sense. There is no native HLS players available in browsers (except as for iOS which is way too specific to target).

**Comment by guypaskar** [comment]
For example, I know few video websites that would like to use hls when possible but they do not want to duplicate their library. (They have mp4 library currently).

The idea , is to download the file as mp4  convert it to ts files and feed it to an hls player (not a native one) , say, jwplayer or similar (create the manifest on the fly)

Is this even possible? I'm wondering about supporting all the player's needs like seeking etc.

**Comment by RReverser** [comment]
Even if it's possible, it just doesn't make sense for this project as it's target is exactly to avoid usage of JWPlayer and similar (any Flash-based players actually) and you propose to use those even for regular MPEG04 files which are supported by HTML5 natively.

**Comment by guypaskar** [comment]
When you put it this way, I agree. 

However, html5 supports hls with media source extension, it also supports dash playing which supports mp4.

The thought is , to have one type of file which is mp4 that can be played in both protocols and also natively.

It might not be related to this project but I was wondering to know if it is even possible.
