### ISSUE TITLE
reduce latency by using websocket instead of ts file 

### ISSUE THREAD

**Issue by maty21** [RReverser/mpegts#16]
hi first of all great project 

we have server side that stream mpeg-ts (using ffmpeg)
from what we understood form the demo you send .ts file on each couple of seconds 
we sending live stream from camera and therefore we cant have latency that is higher than one second 
questions:
1. is it possible  to achieve using your library, latency that is smaller than 1 sec? 
2. if so, is it possible to stream the data directly(using websocket) to the client  and transcoding it to h264, and in that way to reduce the latency ?
3. if no do you have any idea if it possible to achieve that goal Otherwise 

thanks in advance

matyz

**Comment by RReverser** [comment]
> from what we understood form the demo you send .ts file on each couple of seconds

No, it's being sent as soon as available (without extra latency but conversion itself which is pretty fast compared to playback). Websocket won't help here, as the main issue is absence of native support and thus you always will have subtle difference between source stream and output.

P.S. Sorry for missing this issue.
