### ISSUE TITLE
Use MSE ?

### ISSUE THREAD

**Issue by osmestad** [RReverser/mpegts#17]
Just wondering if you have considered using a Video element for display and feeding it with data using MSE (http://html5-demos.appspot.com/static/media-source.html)?
I am wondering if this could help avoid the glitches between segments currently experienced.

**Comment by RReverser** [comment]
I did, but, at least at that moment H.264 wasn't supported in most MSE implementations. Not sure what is the current status of this.

**Comment by osmestad** [comment]
If this feature test is to be belived:
https://www.youtube.com/html5
It currently says OK for "MSE & H.264" in: Chrome (42), Safari (8)
And fails for: Opera (25), Firefox (37)
On OSX (haven't tested on Windows/Linux).

A better overview Is here:
http://www.jwplayer.com/html5/mediasource/

**Comment by osmestad** [comment]
The overview page was moved it seems: http://www.jwplayer.com/mediasource/

**Comment by FranklinWaller** [comment]
The MediaSource extension seems to be (ok) supported. Only Firefox has some whitelist issues. The rest seems to be able to support it.

**Comment by nickdesaulniers** [comment]
^ is accurate.  http://nickdesaulniers.github.io/netfix/#/5/1

**Comment by RReverser** [comment]
Yes, but still has problems which prevent smooth streaming: https://github.com/RReverser/mpegts/issues/20#issuecomment-113539572

**Comment by RReverser** [comment]
Closing this issue in favor of merged discussion in #20.
