### ISSUE TITLE
Exception on input file created by ffmpeg

### ISSUE THREAD

**Issue by MaMazav** [RReverser/mpegts#18]
I wanted to try this library on a static .ts file (rather than HLS protocol).

Just for the trial, I added a line in file browser.js that replaces the URLs returned by HLS server, so the code looks like:
    originals = originals.slice(originals.lastIndexOf(lastOriginal) + 1);
    originals = ['400k00001.ts']; // Override returned URLs
    lastOriginal = originals[originals.length - 1];

I put 400k00001.ts in the same directory as the published web pages and it works great.

Now I tried to replace the mentioned file with one converted by ffmpeg.
I used ffmpeg this way:
ffmpeg  -i 400k00001.ts -f mpegts 400k00001_after_ffmpeg.ts
(tried also with -vcodec libx264 -acodec libvo_aacenc)

I copied the 400k00001_after_ffmpeg.ts file to the published webpages directory and replaced the filename with the new one. I get "Offsets are out of bounds" error.
The file is opened by VLC (very low quality, but opened).

Is that a bug or I just missed something?

EDIT: Working using -vcodec copy -acodec copy. What kind of codecs should I use to transcode an existing video file (which does not natively fit the wanted format)?

Thanks

**Comment by gliese1337** [comment]
I'm seeing something similar. It gets thrown somewhere inside the calle to "nalStream.read('NALUnit');"

**Comment by RReverser** [comment]
Regular MPEG-TS files won't work since they use same format but have different structure from stream chunks.
