### ISSUE TITLE
Weird PES Packet Lengths

### ISSUE THREAD

**Issue by gliese1337** [RReverser/mpegts#19]
PES packets should never be longer than 188 bytes, including the header. Thus, the body data should always be less than that. If I put a breakpoint at https://github.com/RReverser/mpegts/blob/2f5aa31445a7f84fd6384dbbf5dcdd066e2593c6/mpegts_to_mp4/index.js#L44 in the Chrome developer console, though, I'm seeing the size of packet.data range all over the place- as low as 24 bytes (which make sense) and as high as 7319, which is ridiculous. Where are these huge sizes coming from?

When I run the same .ts files through a command-line MPEG-TS inspection utility, all of the packet sizes come out looking normal, so I'm guessing the PES parser here must be doing something beyond _just_ extracting packets- but what?

**Comment by gliese1337** [comment]
Never mind, figured it out myself- it seems obvious in retrospect. The PES reader is just concatenating the data from multiple TS packets in between Payload Unit Start Indicators, which is entirely sensible.

**Comment by RReverser** [comment]
Yeah, exactly. Sorry for getting to this so long, but happy that you figured it out on your own.
