### ISSUE TITLE
Image decoding using h264

### ISSUE THREAD

**Issue by ssleptsov** [RReverser/mpegts#2]
Hi, great project. I will be very appreciate if you can help me with some questions.
1. Each frame is draw in canvas, right? So it's simple image?
2. I have ArrayBuffer that contains image but it's encoded in h264, is it possible to convert such bytes to normal bytes(rgb I think or what need to draw it on canvas) and then simple draw on canvas.
Thanks

**Comment by RReverser** [comment]
Hi, no, I don't actually decode H.264 images but use browser's native abilities for that. You may want to pack your image into, for example, MP4 by wrapping into corresponding binary structure, or have look at https://github.com/mbebenita/Broadway for decoder emscripten-converted implementation in JS.
