### ISSUE TITLE
Demo source code example  is not working on firefox nightly 

### ISSUE THREAD

**Issue by ranjithgithub** [RReverser/mpegts#24]
Hi ,

I am a newbie to HTTP live stream protocol  , So my issue may seem quite obvious.

After downloading the source I have used Firefox nightly PC version browser  for checking the example  .Nightly browser is not showing any HTTP live content, I have noticed below logs in the console

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://crossorigin.me/http://d3sporhxbkob1v.cloudfront.net/bill/vod/sample-video/400k.m3u8. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

I need help in running the demo code on Firefox nightly browser.

**Comment by RReverser** [comment]
You should not download it, but visit online at http://rreverser.github.io/mpegts/. It won't work locally due to security limitations.

**Comment by ranjithgithub** [comment]
I am trying to make  web application out of the source code  , so can you please guide to build a web application?

**Comment by RReverser** [comment]
Um, are you trying to clone my web app into own one? Because if not, I don't really understand your intentions and needs.

**Comment by ranjithgithub** [comment]
I have cloned code form https://github.com/RReverser/mpegts.git.
used same web app included in the code for testing. 
My intention was to test different HTTP live streaming contents by changing the "data-hls" attribute.  I am doing something  wrong here ?

**Comment by ranjithgithub** [comment]
Hi,
I would like to know if my approach in previous comment is meaningful?
If so please guide in resolving the "Cross-Origin Request Blocked" issue.

**Comment by RReverser** [comment]
It just works without installation, but you need local server. Also, you might want to see #21.
