### ISSUE TITLE
Convert blob transport stream to mp4

### ISSUE THREAD

**Issue by switz** [RReverser/mpegts#25]
If I have a Blob of transport streams in my browser, can I convert that into an mp4 Blob? Instead of playing the video back, I'd just like to get the raw data converted from `.ts` to `.mp4`.

Thanks for a cool library!

**Comment by RReverser** [comment]
Sure. Node.js endpoint does that as following: https://github.com/RReverser/mpegts/blob/gh-pages/node.js#L37
