### ISSUE TITLE
Excess video data in mdat box

### ISSUE THREAD

**Issue by gliese1337** [RReverser/mpegts#26]
I've been stepping through the transmuxing code in Chrome developer tools and I noticed something rather odd: if you check the size of the H.264 data that has been written to `stream` right before constructing the MP4 file, but then save the resulting MP4 file and inspect it in a hex editor, the size of the video data in the mdat box is significantly larger in the final file than the size of the video data that was actually written into `stream`.

Furthermore, if you call `stream.getBytes(stream.tell(), 0)` in the console to see what bytes are actually supposed to be written, and then compare that with the contents of the final MP4 file, the exact contents of `stream` are in fact a prefix of the actual mdat data- so, all the correct stuff is there, but then a bunch of junk has just been apparently randomly tacked on the end.

What is that stuff and where is it stuff coming from?

**Comment by RReverser** [comment]
Hmm, are you sure you're not just observing [beginning of the `moov` atom](https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js#L463-L483) right after `mdat`?

**Comment by gliese1337** [comment]
Quite certain. The boundaries of atoms are fairly obvious on visual inspection.

These are the last few bytes of the video data (in ASCII, because it's easier to see patterns that way) for one of the video segments I've tested: `IÖ*ë/“~ºêâwïË`

The next few bytes after that look like this: `!Ïÿÿÿÿ¡µR˜T`

The first few bytes of the moov atom look like this: `:Émoov   lmvhd`
and occur 82352 bytes later. That's 82352 bytes (in this particular instance) of random/compressed-looking junk with no obvious patterns.

**Comment by RReverser** [comment]
> Furthermore, if you call stream.getBytes(stream.tell(), 0) in the console to see what bytes are actually supposed to be written

At which point are you calling it in console? Is there a chance that it might be an [audio](https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js#L162) being added after you logged it?

If that's not it, honestly, I don't have better suggestions at the moment on why you might be seeing a difference.

**Comment by gliese1337** [comment]
I'm checking it [here](https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js#L167), which should be after any audio data is written, and tested with [this line](https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js#L41) commented out so that no audio data should be written anyway.

A little further testing indicates that the extra data is indeed identical to the audio data. So now the mystery is, how the heck does audio data end up in the file (which does in fact not have any audio when you play it back) given that said audio data does not show up when calling `stream.getBytes(stream.tell(), 0)`....

Guess I'll do a little more playing around and let you know if anything sensible turns up.

**Comment by RReverser** [comment]
> which does in fact not have any audio when you play it back

Actually it does (if original file contained valid AAC too). You can see that in online demo as well.

**Comment by gliese1337** [comment]
Oh, I know the videos are supposed to have audio. Getting them to work with audio is the easy, default bit. The weird part is when I comment things out and make alterations with the intention of _removing_ audio, and in fact succeed such that the video playback is now silent (and verify that the video file itself is silent by saving a blob URL to disk and playing it in Windows Media, so it's not just accidentally muting the web page), and then find that the audio data nevertheless is still present in the file.....

**Comment by RReverser** [comment]
Ah, I missed that you were talking about post-commented code. Thought you were trying to say that library doesn't work with audio at all. Sorry for confusion :)
