### ISSUE TITLE
Local installation problem

### ISSUE THREAD

**Issue by mrakus1** [RReverser/mpegts#28]
Hello.

I tried to use your package in local computer. I downloaded zip archive, unpacked it. Go to root directory and make 'npm install'

After that i opened index.html and in my Firefox ( 41.0.2) i had the error message:

23:52:27.880 Error: importScripts failed for jbinary at //jdataview.github.io/dist/jbinary.js
http://requirejs.org/docs/errors.html#importscripts1 require.js:8:0

What i should to do to fix this problem?

Thank you.

**Comment by RReverser** [comment]
You had to use static HTTP server to open it.
