### ISSUE TITLE
TypeError in worker.js when processing video without audio

### ISSUE THREAD

**Issue by NickHowden** [RReverser/mpegts#3]
Hi, Thanks for releasing a great project - hopefully one day mpeg2ts will be treated as a first class video container format by the leading web browsers but in the meantime this is brilliant.

In worker.js:463 I get a TypeError: Cannot read property 'profileMinusOne' of underfined when processing a video stream with no associated audio streams.

**Comment by RReverser** [comment]
Sorry, I don't have video-without-audio sample to test it on. Could you please try moving `trak` array (at line 235) to separate variable and conditionally `.push(...)` it's second element only when `audioSize > 0`?

**Comment by NickHowden** [comment]
Yes, that works perfectly. Many thanks for the speedy response.

Nick

**Comment by RReverser** [comment]
Could you please commit that and send pull request so this issue won't appear for new users?
