### ISSUE TITLE
Live thumbnails generation

### ISSUE THREAD

**Issue by iongion** [RReverser/mpegts#33]
This is not an issue, it is a question - no such feature on github except than abusing labels.

Is it possible to use the h264 parser to extract a keyframe near a timestamp ?
I currently do this with ffmpeg which is smart enough to do `byte-ranges` request, which is very efficient but still needs caching and CDNs support.

What I would like to do is to perform all this client side, browsers are able to:
- Parse the header of the mpeg-ts file
- From the header, find the byte address where the keyframe nearest to the input timestamp exist
- Issue bytes-ranges requests
- Download, process/parse and generate binary data
- Extract the keyframe byes and convert them to something useful
- Load the pixels into a canvas or such

Will this project offer the ability to parse the mpeg-ts header and navigate to a a keyframe in h264 stream contained in the mpeg-ts segment ?

**Comment by RReverser** [comment]
Generally this should be totally possible, except I didn't really parse keyframes and can't help with the image encoding format.

Is there any particular reason you don't want to go the easier way - just creating temporary `<video src>`, setting time to the needed one, starting load manually with `.load` (then browser will send range request as well) and drawing that video element to the canvas?
