### ISSUE TITLE
Demo not working, 403 forbidden

### ISSUE THREAD

**Issue by TheNotary** [RReverser/mpegts#35]
I'm testing out the demo at http://rreverser.github.io/mpegts/ and just seeing the loading wheel spin.  When I look at the console, I see the error:

```
browser.js:148 
GET http://d3sporhxbkob1v.cloudfront.net/bill/vod/sample-video/400k.m3u8 403 (Forbidden)
```

Tried in both firefox and chrome.

**Comment by ralyodio** [comment]
try the cpan feed

**Comment by TheNotary** [comment]
Could you elaborate on that a bit?

**Comment by ralyodio** [comment]
http://cspan1-lh.akamaihd.net/i/cspan1_1@304727/master.m3u8

**Comment by broyeztony** [comment]
Hi there,

Above url does not work for me. Assumed it is the master - child m3u8 structure and need to feed in the end target m3u8 that has the .ts segment.

Managed to see the load / converted console message using the classic: 
http://184.72.239.149/vod/smil:BigBuckBunny.smil/chunklist_w1519320440_b560000.m3u8

But somehow i only hear the sound and not see any video.

Any idea ?

Also, noticed the hiccups in the sound when the new converted segment is produced.

Congrats for the great work.

**Comment by RReverser** [comment]
Feel free to PR any working URL :)

**Comment by RReverser** [comment]
Ok finally found some good-looking and working stream, updated demo.
