### ISSUE TITLE
non-ios usage

### ISSUE THREAD

**Issue by rares-lupascu** [RReverser/mpegts#36]
hey

i see the library is promote as "apple ...." but from what i see there are only js files ... am i wrong to assume it can be used in any JS context? (react native, phonegap or web)

thanks,
Rares

**Comment by RReverser** [comment]
It's not promoted as "apple" certainly :) I don't know why you decided so.

**Comment by rares-lupascu** [comment]
i assumed because of this "This is Apple HTTP Live Streaming JavaScript player created by performing realtime ...."

can i at least ask if i can use it to display the result of Google's Open Spherical Camera API method called "camera.getLivePreview"? they say it returns motion jpeg as binary data

i did not manage to parse the response ... that's how i ended up here

thanks

**Comment by RReverser** [comment]
And, as you could see, `Apple HTTP Live Streaming` is a link in README because it's name of the format (`Apple` relates to format being developed by Apple, not to library).
