### ISSUE TITLE
Parse Google Open Spherical Camera live preview

### ISSUE THREAD

**Issue by rares-lupascu** [RReverser/mpegts#37]
hi

can i use this library to display the result of Google's Open Spherical Camera API method called "camera.getLivePreview"? they say it returns motion jpeg as binary data ... so far i did not manage to parse the response ... 
i am asking because i could not find any kind of docs or examples with the use case i am interested in

thanks

**Comment by RReverser** [comment]
No, as you could see in docs and in previous responses, it parses Apple HLS format - not motion jpeg.
