### ISSUE TITLE
Disable debug log?

### ISSUE THREAD

**Issue by phamvinhthanh** [RReverser/mpegts#9]
Hi RReverser,

(What's your name :) ?)
How can I disable debug log? I think firefox lag issue is from writing debug to console log.

**Comment by RReverser** [comment]
@phamvinhthanh Name is easy to see in profile :)

> How can I disable debug log? I think firefox lag issue is from writing debug to console log.

Not sure about that since this lag exists in Chrome as well, but you can add conditional flag for logs and send PR if that helps.

**Comment by RReverser** [comment]
@phamvinhthanh Tried to turn off all the `console` calls locally - didn't help at all. Unfortunately.
